const mongoose = require("mongoose");

const ComponentSchema = mongoose.Schema({
  content: {
    reviews: [{ type: mongoose.Schema.Types.ObjectId, ref: "Review" }],
    blogs: [{ type: mongoose.Schema.Types.ObjectId, ref: "Blog" }],
    articles: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Article",
      },
    ],
    quizs: [{ type: mongoose.Schema.Types.ObjectId, ref: "Quiz" }],
  },
  sectionArea: { type: String },
  img: [
    {
      name: { type: String },
      sectionArea: { type: String },
      alt: { type: String },
      type: { type: String },
      background: { type: String },
      code: { type: String },
      height: { type: String },
      width: { type: String },
      sectionOrdinality: { type: Number },
      compStyle: { type: String },
      componentName: { type: String },
    },
  ],
  vid: [
    {
      url: { type: String },
      sectionArea: { type: String },
      height: { type: String },
      type: { type: String },
      width: { type: String },
      autoplay: { type: String },
      sectionOrdinality: { type: Number },
      compStyle: { type: String },
      componentName: { type: String },
    },
  ],
  h: [
    {
      headingSize: { type: String },
      sectionArea: { type: String },
      text: { type: String },
      font: { type: String },
      color: { type: String },
      type: { type: String },
      fontStyle: { type: String },
      background: { type: String },
      faIcon: { type: String },
      faIconPosition: { type: String },
      sectionOrdinality: { type: Number },
      compStyle: { type: String },
      componentName: { type: String },
    },
  ],
  p: [
    {
      type: { type: String },
      sectionArea: { type: String },
      text: { type: String },
      fontStyle: { type: String },
      font: { type: String },
      color: { type: String },
      background: { type: String },
      sectionOrdinality: { type: Number },
      compStyle: { type: String },
      componentName: { type: String },
    },
  ],
  li: [
    {
      sectionArea: { type: String },
      type: { type: String },
      text: { type: String },
      font: { type: String },
      color: { type: String },
      background: { type: String },
      listName: { type: String },
      faIcon: { type: String },
      faIconPosition: { type: String },
      fontStyle: { type: String },
      sectionOrdinality: { type: Number },
      compStyle: { type: String },
      componentName: { type: String },
    },
  ],
  a: [
    {
      sectionArea: { type: String },
      text: { type: String },
      url: { type: String },
      type: { type: String },
      faIcon: { type: String },
      buttonStyle: { type: String },
      faIconPosition: { type: String },
      fontStyle: { type: String },
      font: { type: String },
      background: { type: String },
      color: { type: String },
      sectionOrdinality: { type: Number },
      compStyle: { type: String },
      componentName: { type: String },
    },
  ],
  button: [
    {
      type: { type: String },
      text: { type: String },
      action: { type: String },
      actionComponent1: { type: String },
      actionComponent2: { type: String },
      attachedContent: { type: String },
      simulatedState: { type: String },
      code: {
        importStatements: [{ type: String }],
        funcCode: [{ type: String }],
        actionComponent1: { type: String },
        actionComponent2Load: { type: String },
        actionComponent2Revert: { type: String },
      },
      sectionArea: { type: String },
      font: { type: String },
      color: { type: String },
      background: { type: String },
      faIcon: { type: String },
      faIconPosition: { type: String },
      sectionOrdinality: { type: Number },
    },
  ],

  icon: [
    {
      type: { type: String },
      sectionArea: { type: String },
      faIcon: { type: String },
      background: { type: String },
      color: { type: String },
      sectionOrdinality: { type: Number },
    },
  ],

  componentString: { type: String },
});

module.exports = mongoose.model("component", ComponentSchema);
